### ISSUE TITLE
Enable Eslint import order rule

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/foundry#108]
## Suggested feature

[Inspired by the website team](https://github.com/sumup/website/pull/1578) I suggest we enable Eslint's [`import/order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) rule. It enforces a convention in the order of `require()` / `import` statements. The `--fix` option on the command line automatically fixes problems reported by this rule. 

A lot of projects at SumUp more or less follow this convention already. We use the related [`import/first`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md) rule which already enforces that absolute imports come before relative ones, however, it cannot be auto-fixed. This is especially annoying when using VS Code's auto-import feature. The new rule would automate this.

## Alternatives

Continue to manually organize the imports.

## Potential downsides

This should probably be treated as a breaking change since it will lead to many changes when it's first applied to an existing codebase.

**Comment by hleote** [comment]
If we can easily fix the imports using `--fix` sounds like a good idea to me 👍 💯

**Comment by connor-baer** [comment]
Implemented in #109.
