### ISSUE TITLE
Prettier - Does override config work?

### ISSUE THREAD

**Issue by voronianski** [sumup-oss/foundry#198]
## Summarize the question

Seems like Prettier config doesn't respect overrides. Or I'm doing smth wrong here?

## Context

![image](https://user-images.githubusercontent.com/974035/105421159-f2bc7a00-5c41-11eb-80d7-11d383f8a9db.png)

## Specifications

- Package version: 3.1.3
- Node version: 12.20.1
- OS name & version: Mac OS 10.14.4

**Comment by connor-baer** [comment]
Overrides are always the second argument, the first being reserved for other config options (which Foundry's `prettier` config currently doesn't have). Try adding an empty object as the first argument:

```ts
module.exports = require('@sumup/foundry/prettier')({}, {
	trailingComma: 'none'
});
```

**Comment by voronianski** [comment]
thanks a lot! missed this completely :(
